#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 13, 2019 10:56:07 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import v_mainpage_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = main (root)
    v_mainpage_support.init(root, top)
    root.mainloop()

w = None
def create_main(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = main (w)
    v_mainpage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_main():
    global w
    w.destroy()
    w = None

class main:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("518x311+396+112")
        top.title("Anonymous Chat")
        top.configure(background="#31BA7F")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.058, rely=0.161, height=56, width=303)
        self.Label1.configure(activebackground="#31BA7F")
        self.Label1.configure(activeforeground="#ffffff")
        self.Label1.configure(background="#31BA7F")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 28 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''Anonymous Chat''')
        self.Label1.configure(width=303)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.058, rely=0.354, height=27, width=218)
        self.Label2.configure(background="#31BA7F")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 12")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''Enjoy the sensation of chatting''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.058, rely=0.45, height=21, width=184)
        self.Label3.configure(background="#31BA7F")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 12")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(text='''without having to register''')
        self.Label3.configure(width=184)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.058, rely=0.547, height=27, width=153)
        self.Label4.configure(background="#31BA7F")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 12")
        self.Label4.configure(foreground="#ffffff")
        self.Label4.configure(text='''an account and login.''')
        self.Label4.configure(width=153)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.637, rely=0.707, height=54, width=147)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 16 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Start Chat!''')
        self.Button1.configure(width=147)

if __name__ == '__main__':
    vp_start_gui()





