#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 13, 2019 01:49:27 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import v_room_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    root.resizable(False, False)
    v_room_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    v_room_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x319+331+159")
        top.title("Anonymous Chat")
        top.configure(background="#31BA7F")
        top.configure(highlightbackground="#00ff00")
        top.configure(highlightcolor="#00ff00")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.15, rely=0.313, relheight=0.392, relwidth=0.708)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#31BA7F")
        self.Frame1.configure(highlightcolor="#ffffff")
        self.Frame1.configure(width=425)

        self.room1 = ttk.Button(self.Frame1)
        self.room1.place(relx=0.094, rely=0.16, height=25, width=76)
        self.room1.configure(takefocus="")
        self.room1.configure(text='''1''')

        self.room2 = ttk.Button(self.Frame1)
        self.room2.place(relx=0.306, rely=0.16, height=25, width=76)
        self.room2.configure(takefocus="")
        self.room2.configure(text='''2''')

        self.room3 = ttk.Button(self.Frame1)
        self.room3.place(relx=0.518, rely=0.16, height=25, width=76)
        self.room3.configure(takefocus="")
        self.room3.configure(text='''3''')

        self.room4 = ttk.Button(self.Frame1)
        self.room4.place(relx=0.729, rely=0.16, height=25, width=76)
        self.room4.configure(takefocus="")
        self.room4.configure(text='''4''')

        self.room5 = ttk.Button(self.Frame1)
        self.room5.place(relx=0.094, rely=0.4, height=25, width=76)
        self.room5.configure(takefocus="")
        self.room5.configure(text='''5''')

        self.room6 = ttk.Button(self.Frame1)
        self.room6.place(relx=0.306, rely=0.4, height=25, width=76)
        self.room6.configure(takefocus="")
        self.room6.configure(text='''6''')

        self.room7 = ttk.Button(self.Frame1)
        self.room7.place(relx=0.518, rely=0.4, height=25, width=76)
        self.room7.configure(takefocus="")
        self.room7.configure(text='''7''')

        self.TButton8 = ttk.Button(self.Frame1)
        self.TButton8.place(relx=0.729, rely=0.4, height=25, width=76)
        self.TButton8.configure(takefocus="")
        self.TButton8.configure(text='''8''')

        self.room9 = ttk.Button(self.Frame1)
        self.room9.place(relx=0.094, rely=0.64, height=25, width=76)
        self.room9.configure(takefocus="")
        self.room9.configure(text='''9''')

        self.room10 = ttk.Button(self.Frame1)
        self.room10.place(relx=0.306, rely=0.64, height=25, width=76)
        self.room10.configure(takefocus="")
        self.room10.configure(text='''10''')
        self.room10.configure(width=76)

        self.room11 = ttk.Button(self.Frame1)
        self.room11.place(relx=0.518, rely=0.64, height=25, width=76)
        self.room11.configure(takefocus="")
        self.room11.configure(text='''11''')

        self.room12 = ttk.Button(self.Frame1)
        self.room12.place(relx=0.729, rely=0.64, height=25, width=76)
        self.room12.configure(takefocus="")
        self.room12.configure(text='''12''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.117, rely=0.219, height=26, width=89)
        self.Label1.configure(background="#31BA7F")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 11")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Select room:''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.517, rely=0.031, height=51, width=263)
        self.Label2.configure(activebackground="#31BA7F")
        self.Label2.configure(background="#31BA7F")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#f0f0f0")
        self.Label2.configure(text='''Anonymous Chat''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.533, rely=0.784, height=21, width=164)
        self.Label3.configure(background="#31BA7F")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''or Create your own room!''')
        self.Label3.configure(width=164)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.8, rely=0.784, height=24, width=80)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Create room!''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





