#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 13, 2019 11:18:07 AM +07  platform: Windows NT

import sys
import ClientApp as CA
from functools import partial



try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import v_username_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Box___Take_a_Username (root)	
    v_username_support.init(root, top)
    root.resizable(False, False)
    root.mainloop()

w = None
def create_Box___Take_a_Username(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Box___Take_a_Username (w)
    v_username_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Box___Take_a_Username():
    global w
    w.destroy()
    w = None

class Box___Take_a_Username:
    def __init__(self, top=None):

        username = tk.StringVar()
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("352x182")
        top.title("Anonymous Chat")
        top.configure(background="#31BA7F")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.FrameBox = tk.Frame(top)
        self.FrameBox.place(relx=0.028, rely=0.055, relheight=0.896
                , relwidth=0.94)
        self.FrameBox.configure(relief='groove')
        self.FrameBox.configure(borderwidth="2")
        self.FrameBox.configure(relief="groove")
        self.FrameBox.configure(background="#31BA7F")
        self.FrameBox.configure(highlightbackground="#d9d9d9")
        self.FrameBox.configure(highlightcolor="black")
        self.FrameBox.configure(width=325)

        self.Lets_Chat = tk.Button(self.FrameBox, command=partial(CA.changeName,username.get()))
        self.Lets_Chat.place(relx=0.393, rely=0.736, height=24, width=87)
        self.Lets_Chat.configure(activebackground="#31BA7F")
        self.Lets_Chat.configure(activeforeground="#ffffff")
        self.Lets_Chat.configure(background="#31BA7F")
        self.Lets_Chat.configure(disabledforeground="#a3a3a3")
        self.Lets_Chat.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Lets_Chat.configure(foreground="#ffffff")
        self.Lets_Chat.configure(highlightbackground="#d9d9d9")
        self.Lets_Chat.configure(highlightcolor="#ffffff")
        self.Lets_Chat.configure(pady="0")
        self.Lets_Chat.configure(text='''Let's Chat''')



        self.Kembali = tk.Button(self.FrameBox)
        self.Kembali.place(relx=0.695, rely=0.736, height=24, width=88)
        self.Kembali.configure(activebackground="#31BA7F")
        self.Kembali.configure(activeforeground="#ffffff")
        self.Kembali.configure(background="#31BA7F")
        self.Kembali.configure(disabledforeground="#a3a3a3")
        self.Kembali.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Kembali.configure(foreground="#ffffff")
        self.Kembali.configure(highlightbackground="#d9d9d9")
        self.Kembali.configure(highlightcolor="#ffffff")
        self.Kembali.configure(pady="0")
        self.Kembali.configure(text='''Kembali''')

        self.txtUsername = tk.Entry(self.FrameBox, textvariable=username)
        self.txtUsername.place(relx=0.045, rely=0.399, height=30, relwidth=0.912)

        self.txtUsername.configure(background="#ffffffffffff")
        self.txtUsername.configure(disabledforeground="#a3a3a3")
        self.txtUsername.configure(font="TkFixedFont")
        self.txtUsername.configure(foreground="#000000")
        self.txtUsername.configure(highlightbackground="#d9d9d9")
        self.txtUsername.configure(highlightcolor="black")
        self.txtUsername.configure(insertbackground="black")
        self.txtUsername.configure(justify='center')
        self.txtUsername.configure(selectbackground="#c4c4c4")
        self.txtUsername.configure(selectforeground="black")

        self.Label1 = tk.Label(self.FrameBox)
        self.Label1.place(relx=0.03, rely=0.123, height=34, width=173)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#31BA7F")
        self.Label1.configure(disabledforeground="#31BA7F")
        self.Label1.configure(font="-family {Segoe UI} -size 15 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Take a Username:''')

if __name__ == '__main__':
    vp_start_gui()





